import { describe, it, expect } from 'vitest'
import { generate } from '../generate'
import { format } from '../format'
import { isValid } from '.'

describe('IsValid', () => {
  it('Validate rut generated by the fuction generate', () => {
    expect(isValid(generate())).toBeTruthy()
  })

  it('Validate rut length 7', () => {
    expect(isValid('9264930')).toBeTruthy()
  })

  it('Validate rut generated by the fuction generate and format', () => {
    expect(isValid(format(generate()))).toBeTruthy()
  })

  it('Invalidate rut', () => {
    expect(isValid('123456789')).toBeFalsy()
  })

  it('Invalidate rut with format', () => {
    expect(isValid(format('123456789'))).toBeFalsy()
  })
})
